### ISSUE TITLE
Can't get it working in some VS2017.2 projects

### ISSUE THREAD

**Issue by 304NotModified** [rich-newman/typescript-analyzer#10]
Can't get this working, also on other machines. Is there somewhere a debug log to see?

**Comment by rich-newman** [comment]
There's no debug log as such in the production version.  Errors appear in the Output window under 'Show output from:' TypeScript Analyzer. The entry only appears in the dropdown if there actually are any errors from the TypeScript Analyzer.  

If you have the 'Node.js development' workload installed easiest to get going is to create a **TypeScript** 'Blank Node.js Console Application' from a Visual Studio session with TypeScript Analyzer installed.  Then right-click the project in Solution Explorer and you should see a context menu option 'Run TypeScript Analyzer'.  If you do this it should show three tslint errors in the Error List (View/Error List), one of which is no-console.

**Comment by 304NotModified** [comment]
thanks for the input, I will try it.

**Comment by 304NotModified** [comment]
got the menus, but after 
`Run TypeScript Analyzer`, nothing happens. No error/warning in the error-list, nothing in the output window.

maybe this is the issue.

![image](https://user-images.githubusercontent.com/5808377/27598664-766a7022-5b66-11e7-9b45-242d22f1b8b2.png)

I have TS 2.1

I see this is: https://github.com/Microsoft/nodejstools/issues/1603

Not sure if this could cause the problem

**Comment by 304NotModified** [comment]
**update:**

I see the problem, it only reports errors if the open files. Is this by design? It's really confusing.

**Comment by rich-newman** [comment]
It should work if you do 'Run TypeScript Analyzer' even if there are no files open, and it should lint at the level you click in the Solution Explorer.  So if you rightclick one file it should lint that file only, rightclick a project it should lint all files in the project.  But otherwise, yes, it lints a file when you open it or save it.  I inherited this behavior from the code I forked, and I think the VS team have changed it for the linters they've moved in to VS itself (ESLint etc), so they clearly agree with you.  I've also added a 'Run on build' option, which is off by default, but can be found in Tools/Options/TypeScript Analyzer

**Comment by 304NotModified** [comment]
> It should work if you do 'Run TypeScript Analyzer' even if there are no files open, and it should lint at the level you click in the Solution Explorer

Unfortunately that won't work, also not for the new node project.

> I've also added a 'Run on build' option, which is off by default, but can be found in Tools/Options/TypeScript Analyzer

Even when enabled, it only works for the open files :(

When I see the error in the error list, and I close the file, the error is also removed.

Can't image it's because of R#

Any glues how to get it working? Or how I get a better diagnostics?

**Comment by rich-newman** [comment]
I just installed Resharper in a VM and it works fine with the TypeScript Analyzer.  So it's not that.

I also had a look at the code.  There isn't any obvious reason why it might work on opening a file and not if explicitly run.  In the end it calls the same method, although it has to do some work identifying files for an explicit run that might conceivably fail.  Are your files in an odd place, or linked in rather than being in the project folder or something like that?

I can put some diagnostics in and release.  We probably need this anyway.  In the meantime can you tell me what version of VS you have from Help/About Microsoft Visual Studio please? (I'm mainly using VS 2017 Community 15.2 (26430.14)).  Is it an ASP.NET project that has the problems, or any type?  Does your VS install have any other quirks or things that don't work?  Any other clues you can give me?!

**Comment by 304NotModified** [comment]
First of all, thanks for the support!

After reboot is suddenly worked. Unfortunately it only works in a small/new projects (tested node and ASP.NET MVC), but not in the project used in my company.  (ASP.NET MVC)

It's a project/solution which has been created initially in VS2012 (and moved to VS2013, VS2015 and VS2017). Do you have any glues what could be the reason? 

I checked the detailed log of the build, but it doesn't show anything about tslint:

![image](https://user-images.githubusercontent.com/5808377/27658093-241b5342-5c4f-11e7-9dbd-666f55349752.png)

Would be great if there was some debug log to check.

I will try to re-create the project in VS2017, but that's hours of work (customized csproj, using paket etc)

**Comment by 304NotModified** [comment]
yes solved!

For some reason there was a linter in the output window (cannot reproduce it), and it shows:

```
29-6-2017 10:40:50: System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 93
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.AddFilesInPath(String path, List`1 files) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 78
   at WebLinterVsix.LintFilesCommandBase.GetBuildFilesToLint(Boolean isBuildingSolution) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 51
   at WebLinterVsix.LintFilesCommandBase.<LintBuildSelection>d__3.MoveNext() in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 43
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at WebLinterVsix.LintFilesCommand.UpdateSolution_Begin(Int32& pfCancelUpdate) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommand.cs:line 61
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 93
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.GetFiles(String path, String pattern) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 95
   at WebLinterVsix.LintFilesCommandBase.AddFilesInPath(String path, List`1 files) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 78
   at WebLinterVsix.LintFilesCommandBase.GetBuildFilesToLint(Boolean isBuildingSolution) in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 51
   at WebLinterVsix.LintFilesCommandBase.<LintBuildSelection>d__3.MoveNext() in C:\Source\typescript-analyzer4\src\WebLinterVsix\Commands\LintFilesCommandBase.cs:line 43<---

```

Also VS2017 was showing a weird message:

> Preview not supported



After checking this was the folder node_modules, with for example the module webpack:

```
c:\temp\project\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\braces\node_modules\expand-range\node_modules\fill-range\node_modules\randomatic\node_modules\kind-of\
```

I've noticed I had a old version of NPM, and newer versions of NPM has a flat history, so I did:

update NPM
```
npm install npm@latest -g
```

remove old node_modules
```
rimraf node_modules
```

reinstalled everything

```
npm install
```

This solved my problem :)

Thanks for the help!
