### ISSUE TITLE
Getting exception in analyze process

### ISSUE THREAD

**Issue by roadrunner6** [rich-newman/typescript-analyzer#20]
For some reason I get an exception in the analyzer code, but it worked fine for 2 weeks. I guess it might be related with the project setup, but I have no idea where the problem might be. This is version 1.11 in Visual Studio 2017 15.3.3. I'm pretty sure the error is in my project itself, but catching this exception and error handling might improve typescript-analyzer.

15.09.2017 14:04:19: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at WebLinterVsix.TableDataSource.FindProjectItems(ProjectItem projectItem, String projectName, Dictionary`2 fileNameToProjectNameMap) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 158
   at WebLinterVsix.TableDataSource.FindProjectItems(ProjectItem projectItem, String projectName, Dictionary`2 fileNameToProjectNameMap) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 161
   at WebLinterVsix.TableDataSource.FindProjectItems(ProjectItem projectItem, String projectName, Dictionary`2 fileNameToProjectNameMap) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 161
   at WebLinterVsix.TableDataSource.FindProjectItems(ProjectItem projectItem, String projectName, Dictionary`2 fileNameToProjectNameMap) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 161
   at WebLinterVsix.TableDataSource.FindProjectItems(ProjectItem projectItem, String projectName, Dictionary`2 fileNameToProjectNameMap) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 161
   at WebLinterVsix.TableDataSource.CreateFileNameToProjectNameMap() in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 148
   at WebLinterVsix.TableDataSource.AddErrors(IEnumerable`1 errors) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\TableDataSource.cs:line 121
   at WebLinterVsix.ErrorListService.ProcessLintingResults(IEnumerable`1 results, String[] fileNames, String[] filterFileNames, Boolean showErrorList) in C:\Source\typescript-analyzer2\src\WebLinterVsix\ErrorList\ErrorListService.cs:line 20
   at WebLinterVsix.LinterService.<Lint>d__3.MoveNext() in C:\Source\typescript-analyzer2\src\WebLinterVsix\LinterService.cs:line 32

**Comment by rich-newman** [comment]
@roadrunner6  Actually that looks like a bug in the Analyzer code, and it looks like it's caused by a ts or tsx file being included in more than one Visual Studio project, with errors in both projects.  That code is just trying to work out which project name to display in the error list.  The code is looking at the full path, so I think the same file must be linked in one or both projects (i.e. included with Add Link, rather than as a regular project file).

We'll add a fix in the next release - perhaps you could have a look at your solution and try to see if what I've described looks possible?

**Comment by rich-newman** [comment]
I have released a version (1.12) that attempts to fix this.  Please let me know if it works.

**Comment by roadrunner6** [comment]
@rich-newman : I will try to check this tomorrow, but the szenario you mentioned looks plausible, because we have two projects and do share files. Thanks alot!

**Comment by roadrunner6** [comment]
@rich-newman I tested 1.12, and can confirm that the issue is gone now. Again, thanks for your excellent work!
