### ISSUE TITLE
VS2017 crash

### ISSUE THREAD

**Issue by neorth** [rich-newman/typescript-analyzer#23]
I got this message from VS after a crash:
![image](https://user-images.githubusercontent.com/8577089/31949158-e870d358-b8d8-11e7-970a-a1d90a50ab5a.png)

Windows Event viewer gives me this error from .NET Runtime:

> Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WebLinterVsix.SinkManager+<>c__DisplayClass6_0.<RemoveSnapshots>b__0(WebLinterVsix.TableEntriesSnapshot)
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at WebLinterVsix.SinkManager.RemoveSnapshots(System.Collections.Generic.IEnumerable`1<System.String>)
   at WebLinterVsix.TableDataSource.CleanErrors(System.Collections.Generic.IEnumerable`1<System.String>)
   at WebLinterVsix.FileListeners.SourceFileCreationListener+<>c__DisplayClass10_0.<TextviewClosed>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

It seems related to this issue: https://github.com/madskristensen/WebAnalyzer/issues/30

Visual Studio 15.4.1, TypeScript Analyzer 1.12

**Comment by rich-newman** [comment]
Thanks for the bug report.  I've had a look, but as you can imagine it's pretty hard to diagnose exactly from just the stack trace.

What I can see is [the line that's causing the problem](https://github.com/rich-newman/typescript-analyzer/blob/ea4b38fa05f33fe3c88bf4c92a63194fbc99f732/src/WebLinterVsix/ErrorList/SinkManager.cs#L52).  This is [code that I have inherited from Mads](https://github.com/madskristensen/WebAnalyzer/blob/da075ae1078827067fef8d61ea20ded640ce1990/src/WebLinterVsix/ErrorList/SinkManager.cs#L52) so it may well be the same issue you mention.  

I think the only way this line can throw that exception is if another thread alters the _snapshots collection at the exact same time this code is trying to execute FirstOrDefault.  However it's not clear how this could happen.  

In any case I'll put some better defense in for the next release.

Of course, it's also possible that something else caused the crash leaving the analyzer's thread execution in a mess and throwing exceptions.

**Comment by rich-newman** [comment]
The latest release (1.13) has some exception handlers that should prevent this code from causing a VS crash at least.  Let me know if you see anything like it again please.

**Comment by rich-newman** [comment]
The fix and additional logging let me work out what was going on here.  The problem arose if you had two or more code windows open.  That is, a code file had been dragged into a separate window.  Then if there were linting errors in the active code files you would intermittently get this error on starting Visual Studio.

The analyzer was running the linter on multiple background threads simultaneously for the active code files in this case, and failing to collate the results correctly because of a threading bug.  Release 1.14 fixes this I think, and also sorts out some problems with the code not dealing with the multiple input files correctly.
