### ISSUE TITLE
No errors listed when tslint.json file extends another file

### ISSUE THREAD

**Issue by ChrisMBarr** [rich-newman/typescript-analyzer#6]
I am running VS 2017 on Windows 10, I have this plugin installed and there are zero errors reported when I open files with linting issues.  I have to fall back to running a gulp task to find all my linting issues.

I get no error messages from this plugin either.  Is there somewhere I can look for a log file?

I do however get these warnings... although unrelated i wonder if they could cause issues here?
![image](https://cloud.githubusercontent.com/assets/463685/26828457/85497ef4-4a8f-11e7-8962-c62a4fa943dc.png)

**Comment by rich-newman** [comment]
Errors appear in the Output window under 'Show output from:' TypeScript Analyzer.  The entry only appears in the dropdown if there actually are any errors from the TypeScript Analyzer.
If you right-click a file in Solution Explorer do you see 'Run TypeScript Analyzer' in the context menu?

**Comment by ChrisMBarr** [comment]
Ah, i was not aware i had to look there.  yes, i have that in the right-click context menu.

When I delete a semicolon or something else to trigger a lint warning and I look in the Output window with "Typescript Analyzer" selected, i and presented with the following:
```
6/6/2017 9:46:38 AM: Newtonsoft.Json.JsonReaderException: Error reading JArray from JsonReader. Current JsonReader item is not an array: String. Path '', line 1, position 95.
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JArray.Parse(String json, JsonLoadSettings settings)
   at WebLinter.TsLintLinter.ParseErrors(String output) in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\TslintLinter.cs:line 17
   at WebLinter.LinterBase.<Lint>d__27.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterBase.<Run>d__26.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterFactory.<LintAsync>d__6.MoveNext() in C:\Source\typescript-analyzer\src\WebLinter\Linting\LinterFactory.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinterVsix.LinterService.<LintAsync>d__4.MoveNext() in C:\Source\typescript-analyzer\src\WebLinterVsix\LinterService.cs:line 66
```

**Comment by rich-newman** [comment]
OK that means the analyzer can't parse the errors coming back from the linter, and that usually means an invalid tslint.json.  I get similar errors if I include an empty tslint.json.

I suggest trying this:

- Start a blank TypeScript node console app if you have it installed (New project/Templates/TypeScript/Blank Node.js Console Application)
- Reset the TypeScript Analyzer (Tools/TypeScript Analyzer/Reset TypeScript Analyzer Settings).  This restores the default tslint.json to the one shipped with the extension
- Right click the console app in Solution Explorer and 'Run TypeScript Analyzer...'

That should show you three linting errors, or at least get rid of the error above.

The default tslint.json it's using is at c:\Users\{username}\tslint.json, and you can see and edit it with Tools/TypeScript Analyzer/Edit TSLint settings.  If you include a tslint.json in the project or solution folder it will override it.

**Comment by ChrisMBarr** [comment]
I was able to mess with my `tslint.json` file and get TypeScript Analyzer to work, so I've narrowed it down to my config file extending another config file.  When this is not present, it works.

Here's is my `./tslint.json` file where I extend another file and enable some different rules.
```json
{
    "extends": [
        "./tslint-rules/tslint.json"
    ],
    "rules": {
        "cyclomatic-complexity": {
            "options": [ 19 ] //TODO: See if we can lower this even more!
        },
        "typedef": {
            "options": [ "parameter", "arrow-parameter", "object-destructuring", "array-destructuring", "arrow-call-signature", "call-signature" ]
        },
        "encoding": false,
        "prefer-const": false,

        //Enable some type-checked rules
        "no-boolean-literal-compare": true,
        "no-cookies": true,
        "no-floating-promises": true,
        "no-for-in-array": true,
        "no-unnecessary-initializer": true,
        "restrict-plus-operands": true
}
```

When I remove the `"extends": [ "./tslint-rules/tslint.json" ],` from this file, it all works as expected.


And below is the file it extends at `./tslint-rules/tslint.json`
```json
{
    "rules": {
        "align": false,
        "adjacent-overload-signatures": true,
        "array-type": {
            "options": ["array"]
        },
        "arrow-return-shorthand": {
            "options": ["multiline"]
        },
        "arrow-parens": true,
        "await-promise": false, //requires type info
        "ban": {
            "options": [
                [ "angular", "each",    "Don't rely on angular to perform loops. Either use a 'for of' loop or the native 'array.forEach': https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_each" ],
                [ "jQuery",  "each",    "Don't rely on jQuery to perform loops. Either use a 'for of' loop or the native 'array.forEach': https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_each" ],
                [ "$",       "each",    "Don't rely on jQuery to perform loops. Either use a 'for of' loop or the native 'array.forEach': https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_each" ],
                [ "_",       "each",    "Don't rely on Underscore to perform loops. Either use a 'for of' loop or the native 'array.forEach': https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_each" ],
                [ "_",       "forEach", "Don't rely on Underscore to perform loops. Either use a 'for of' loop or the native 'array.forEach': https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_each" ],

                [ "$",      "ajax",    "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "jQuery", "ajax",    "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "$",      "get",     "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "jQuery", "get",     "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "$",      "getJSON", "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "jQuery", "getJSON", "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "$",      "post",    "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],
                [ "jQuery", "post",    "Don't rely on jQuery to make AJAX calls. $inject the Angular '$http' service instead" ],

                [ "jQuery", "extend", "Don't rely on jQuery to extend an object, use 'angular.merge', 'angular.extend', or 'angular.copy' instead: http://davidcai.github.io/blog/posts/copy-vs-extend-vs-merge" ],
                [ "$",      "extend", "Don't rely on jQuery to extend an object, use 'angular.merge', 'angular.extend', or 'angular.copy' instead: http://davidcai.github.io/blog/posts/copy-vs-extend-vs-merge" ],
                [ "_",      "extend", "Don't rely on Underscore to extend an object, use 'angular.merge', 'angular.extend', or 'angular.copy' instead: http://davidcai.github.io/blog/posts/copy-vs-extend-vs-merge" ],
                [ "_",      "clone",  "Don't rely on Underscore to shallow copy an object, either use 'angular.extend' to shallow copy, or 'angular.copy' to deep copy: http://davidcai.github.io/blog/posts/copy-vs-extend-vs-merge" ],

                [ "_", "indexOf", "Use the native 'array.indexOf' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_indexof" ],
                [ "_", "lastIndexOf", "Use the native 'array.lastIndexOf' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_lastindexof" ],

                [ "_", "every", "Use the native 'array.every' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_every" ],
                [ "_", "all", "Use the native 'array.every' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_every" ],

                [ "_", "filter", "Use the native 'array.filter' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_filter" ],
                [ "_", "select", "Use the native 'array.filter' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_filter" ],

                [ "_", "includes", "Use the native 'array.indexOf' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_includes" ],
                [ "_", "contains", "Use the native 'array.indexOf' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_includes" ],

                [ "_", "map", "Use the native 'array.map' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_map" ],
                [ "_", "collect", "Use the native 'array.map' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_map" ],

                [ "_", "reduce", "Use the native 'array.reduce' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_reduce" ],
                [ "_", "inject", "Use the native 'array.reduce' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_reduce" ],
                [ "_", "foldl", "Use the native 'array.reduce' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_reduce" ],
                [ "_", "reduceRight", "Use the native 'array.reduceRight' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_reduceright" ],
                [ "_", "foldr", "Use the native 'array.reduceRight' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_reduceright" ],

                [ "_", "some", "Use the native 'array.some' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_some" ],
                [ "_", "any", "Use the native 'array.some' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_some" ],

                [ "_", "has", "Use the native 'myObj.hasOwnProperty(\"someProp\")' instead of using the Underscore library" ],
                [ "_", "keys", "Use the native 'Object.keys(myObj)' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_keys" ],
                [ "_", "size", "Use the native 'array.length' or 'Object.keys(myObj).length' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_size" ],
                [ "_", "values", "Use 'Object.keys(obj).map(key => obj[key])' instead of using the Underscore library" ],
                [ "_", "pluck", "Use the native 'array.map(x => x.prop)' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_pluck" ],

                [ "_", "isString", "Use the native 'typeof someVar == \"string\"' instead of using the Underscore library" ],
                [ "_", "isBoolean", "Use the native 'typeof someVar == \"boolean\"' instead of using the Underscore library" ],
                [ "_", "isFunction", "Use the native 'typeof someVar == \"function\"' instead of using the Underscore library" ],
                [ "_", "isNumber", "Use the native 'typeof someVar == \"number\"' or '!isNaN(someVar)' instead of using the Underscore library" ],
                [ "_", "isFinite", "Use the native 'someVar == Infinity || someVar == -Infinity' instead of using the Underscore library" ],
                [ "_", "isNaN", "Use the native '!isNaN(someVar)' instead of using the Underscore library: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_isnan" ],
                [ "_", "isNull", "Use the native 'someVar == null', or even simpler 'if(!someVar)', instead of using the Underscore library" ],
                [ "_", "isUndefined", "Use the native 'someVar == undefined', or even simpler 'if(!someVar)', instead of using the Underscore library" ],

                [ "_", "first", "Use the native 'array[0]' instead of using the Underscore library" ],
                [ "_", "last", "Use the native 'array[array.length - 1]' instead of using the Underscore library" ],
                [ "_", "union", "Use the native 'array1.concat(array2)' instead of using the Underscore library" ],
                [ "_", "reverse", "Use the native 'array.reverse' instead of using the Underscore library - https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_reverse" ],
                [ "_", "join", "Use the native 'array.join' instead of using the Underscore library - https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_join" ],

                [ "_", "toUpper", "Use the native 'string.toUpperCase()' instead of using the Underscore library - https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_reverse" ],
                [ "_", "toLower", "Use the native 'string.toLowerCase()' instead of using the Underscore library - https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_tolower" ],
                [ "_", "trim", "Use the native 'string.trim()' instead of using the Underscore library - https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_trim" ],

                [ "_", "after", "This can be done natively without using the Underscore library - https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_after" ],

                //Do not allow these "focus" Jasmine test methods!
                ["fdescribe"],
                ["fit"]
            ]
        },
        "ban-types": {
            "options": [
                ["Object", "Avoid using the `Object` type. Did you mean `object`?"],
                ["Function", "Avoid using the `Function` type. Prefer a specific function type, like `() => void`."],
                ["Boolean", "Avoid using the `Boolean` type. Did you mean `boolean`?"],
                ["Number", "Avoid using the `Number` type. Did you mean `number`?"],
                ["String", "Avoid using the `String` type. Did you mean `string`?"],
                ["Symbol", "Avoid using the `Symbol` type. Did you mean `symbol`?"]
            ]
        },
        "callable-types": true,
        "class-name": true,
        "comment-format": false,
        "completed-docs": false,
        "curly": true,
        "cyclomatic-complexity": {
            "options": [20]
        },
        "deprecation": false, //requires type info
        "eofline": false,
        "encoding": true,
        "file-header": false,
        "forin": true,
        "import-blacklist": false,
        "import-spacing": false,
        "indent": [
            false,
            "spaces"
        ],
        "interface-name": {
            "options": [ "always-prefix" ]
        },
        "interface-over-type-literal": false,
        "jsdoc-format": false,
        "label-position": true,
        "linebreak-style": false,
        "match-default-export-name": false, //requires type info
        "max-classes-per-file": false,
        "max-file-line-count": {
            "options": [ 300 ]
        },
        "max-line-length": {
            "options": [200]
        },
        "member-access": false,
        "member-ordering": {
            "options": { "order": "fields-first" }
        },
        "new-parens": true,
        "newline-before-return": false,
        "no-angle-bracket-type-assertion": false,
        "no-any": true,
        "no-arg": true,
        "no-bitwise": true,
        "no-boolean-literal-compare": false, //requires type info
        "no-conditional-assignment": true,
        "no-consecutive-blank-lines": {
            "options": [2]
        },
        "no-console": {
            //allows console.warn & console.error
            "options": [ "assert", "clear", "count", "dir", "dirxml", "exception", "group", "groupEnd", "info", "log", "profile", "profileEnd", "table", "timeEnd", "timeStamp", "trace" ]
        },
        "no-construct": true,
        "no-debugger": true,
        "no-default-export": true,
        "no-duplicate-super": true,
        "no-duplicate-variable": true,
        "no-empty": true,
        "no-empty-interface": true,
        "no-eval": true,
        "no-floating-promises": false, //requires type info
        "no-for-in-array": false, //requires type info
        "no-import-side-effect": false,
        "no-inferrable-types": false,
        "no-inferred-empty-object-type": false, //requires type info
        "no-internal-module": true,
        "no-invalid-template-strings": true,
        "no-invalid-this": {
            "options": [ "check-function-in-method" ]
        },
        "no-irregular-whitespace": true,
        "no-magic-numbers": false,
        "no-mergeable-namespace": false,
        "no-misused-new": true,
        "no-namespace": false,
        "no-non-null-assertion": true, //https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator
        "no-null-keyword": true,
        "no-object-literal-type-assertion": false,
        "no-parameter-properties": false,
        "no-reference": false,
        "no-reference-import": true,
        "no-require-imports": true,
        "no-shadowed-variable": true,
        "no-sparse-arrays": true,
        "no-string-literal": true,
        "no-string-throw": true,
        "no-switch-case-fall-through": true,
        "no-trailing-whitespace": false,
        "no-unbound-method": false, //requires type info
        "no-unnecessary-callback-wrapper": true,
        "no-unnecessary-initializer": true,
        "no-unnecessary-qualifier": false, //requires type info
        "no-unnecessary-type-assertion": false, //requires type info
        "no-unsafe-any": false, //requires type info
        "no-unsafe-finally": true,
        "no-unused-expression": {
            "options": ["allow-fast-null-checks"]
        },
        "no-unused-variable": false, //requires type info
        "no-use-before-declare": false, //requires type info
        "no-var-keyword": true,
        "no-var-requires": true,
        "no-void-expression": false, //requires type info
        "number-literal-format": false,
        "object-literal-key-quotes": false,
        "object-literal-shorthand": false,
        "object-literal-sort-keys": true,
        "one-line": {
            "options": [ "check-open-brace", "check-catch", "check-else", "check-finally", "check-whitespace" ]
        },
        "one-variable-per-declaration": {
            "options": [ "ignore-for-loop" ]
        },
        "only-arrow-functions": true,
        "ordered-imports": false,
        "prefer-conditional-expression": true,
        "prefer-const": true,
        "prefer-for-of": true,
        "prefer-function-over-method": false,
        "prefer-method-signature": false,
        "prefer-object-spread": false,
        "prefer-switch": false,
        "prefer-template": {
            "options": ["allow-single-concat"]
        },
        "return-undefined": false, //requires type info
        "promise-function-async": false, //requires type info
        "quotemark": false,
        "radix": true,
        "restrict-plus-operands": false, //requires type info
        "semicolon": {
            "options": [ "always", "ignore-interfaces", "ignore-bound-class-methods" ]
        },
        "space-before-function-paren": false,
        "strict-boolean-expressions": false, //requires type info
        "strict-type-predicates": false, //requires type info
        "switch-default": true,
        "trailing-comma": {
            "options": {
                "multiline": "never",
                "singleline": "never"
            }
        },
        "triple-equals": {
            "options": [ "allow-null-check", "allow-undefined-check" ]
        },
        "typedef": {
            "options": [ "parameter", "arrow-parameter", "object-destructuring", "array-destructuring"]
        },
        "typedef-whitespace": {
            "options": [ {
                "call-signature": "nospace",
                "index-signature": "nospace",
                "parameter": "nospace",
                "property-declaration": "nospace",
                "variable-declaration": "nospace"
            }, {
                "call-signature": "space",
                "index-signature": "space",
                "parameter": "space",
                "property-declaration": "space",
                "variable-declaration": "space"
            }]
        },
        "typeof-compare": true,
        "unified-signatures": true,
        "use-isnan": true,
        "variable-name": {
            "options": ["check-format", "allow-leading-underscore", "ban-keywords" ]
        },
        "whitespace": {
            "options": [ "check-branch", "check-decl", "check-operator", "check-separator", "check-type" ]
        }
    }
}
```

**Comment by rich-newman** [comment]
**Those tslint.jsons work fine for me**.  I created a node app, threw them in, and it worked first time.

I stuck it on Github, so perhaps you can check it out and see if it works for you too?  I get three linting errors, and if I set "semicolon": false in the big one then the semicolon error goes away.

[https://github.com/rich-newman/tslint.json-extends-test](https://github.com/rich-newman/tslint.json-extends-test)

My only comment is where you have "options" that's wrong, although it works.  I had this wrong in the default tslint.json in my last version (v1.3).  If you look at the default tslint.json in v1.4, released yesterday, it complies with the schema.  For example array-type should be:

"array-type": [ true, "array-simple" ],

**Comment by ChrisMBarr** [comment]
Are you sure?  According the the release notes for version 5.0.0 the `options` syntax is now the required syntax.

https://github.com/palantir/tslint/releases/tag/5.0.0

**Comment by rich-newman** [comment]
No, not sure at all.  I assumed that was the old syntax because the schema used for validation in the [JSON schema store](http://json.schemastore.org/tslint) disallows it.  Of course Visual Studio uses that to validate an open tslint.json.  But I think you may be right: it's the new syntax and the tslint guys haven't updated the schema store.  I'll raise an issue with them.

**Comment by ChrisMBarr** [comment]
Yeah, I've noticed that the documentation for the tslint rules also still uses the old schema/syntax for their examples: https://palantir.github.io/tslint/rules/array-type/

**Comment by rich-newman** [comment]
The tslint guys confirmed that I'm wrong and you are right: the schema store is out of date, palantir/tslint#2900.  The new schemas are actually in the individual rules, making it hard to update it.  I think it means the analyzer's default tslint.json is probably wrong too.

Are you OK with the extender stuff now?

**Comment by adidahiya** [comment]
> According the the release notes for version 5.0.0 the options syntax is now the required syntax.

actually, the old rule option syntax is still supported, along with the new one. some of the docs are stale though.

**Comment by ChrisMBarr** [comment]
Well... I'm actually no longer able to test anything out.  My company only has licenses for VS2015, and I was on the VS2017 trial which has now expired!

I can tell you that before I got the error output I posted above unless I removed the `extends` array.  It happened every time, and that was the only thing I changed that made it work.

I was trying out differen TSLint tools for Visual Studio, and came across [vladeck/TSLint/](https://github.com/vladeck/TSLint), but I had a similar issue with that project.  I was able to [open an issue with that project](https://github.com/vladeck/TSLint/issues/2) and the owner made a fix to support `extends` syntax. I'm not sure if that relates to this project at all, but I thought it might be worth mentioning.

**Comment by rich-newman** [comment]
The Community Edition of VS2017 is free and probably has everything you need: I'm using it.  I had an enterprise license for VS2015 and never used any of the additional features (CodeLens was useful but ground my machine to a halt).  You do need a Microsoft account for VS2017 Community or it throws you out after 30 days, but those are free too.
